name: schowek-z-problemami-psychicznymi
version: ${project.version}
main: pl.memexurer.mschowek.SchowekPlugin
api-version: 1.16
description: duperele :D
depend:
  - PlaceholderAPI
commands:
  schowek:
    alias: [twojastara]